using System;

namespace Terraria
{
	public class Recipe
	{
		public class ItemCreator : Item
		{
			public new object Clone()
			{
				Item item = new Item();
				item.SetDefaults(name);
				item.stack = stack;
				return item;
			}
		}

		public static int nextSimpleRecipe = 0;

		public static int maxRequirements = 15;

		public static int maxRecipes = 400;

		public static int numRecipes = 0;

		public static Recipe newRecipe = new Recipe();

		public Item[] requiredItem = new Item[maxRequirements];

		public int[] requiredTile = new int[maxRequirements];

		public bool needWater;

		public bool needLava;

		public ItemCreator createItem = new ItemCreator();

		public Recipe()
		{
			for (int i = 0; i < maxRequirements; i++)
			{
				requiredItem[i] = new Item();
				requiredTile[i] = -1;
			}
		}

		public void Create(Item I)
		{
			TMod.RunMethod(TMod.WorldHooks.CraftItem, this, I, I.stack == createItem.stack);
			for (int i = 0; i < maxRequirements && requiredItem[i].type != 0; i++)
			{
				int num = requiredItem[i].stack;
				for (int j = 0; j < 48; j++)
				{
					if (Main.player[Main.myPlayer].inventory[j].IsTheSameAs(requiredItem[i]))
					{
						if (Main.player[Main.myPlayer].inventory[j].stack > num)
						{
							Main.player[Main.myPlayer].inventory[j].stack -= num;
							num = 0;
						}
						else
						{
							num -= Main.player[Main.myPlayer].inventory[j].stack;
							Main.player[Main.myPlayer].inventory[j] = new Item();
						}
					}
					if (num <= 0)
					{
						break;
					}
				}
			}
			FindRecipes();
		}

		public static void FindRecipes()
		{
			int num = Main.availableRecipe[Main.focusRecipe];
			float num2 = Main.availableRecipeY[Main.focusRecipe];
			for (int i = 0; i < maxRecipes; i++)
			{
				Main.availableRecipe[i] = 0;
			}
			Main.numAvailableRecipes = 0;
			for (int j = 0; j < maxRecipes && Main.recipe[j].createItem.type != 0; j++)
			{
				bool flag = true;
				bool flag2 = false;
				if (Main.guideItem.type > 0 && Main.guideItem.stack > 0 && Main.guideItem.name != "")
				{
					flag2 = true;
				}
				if (flag2)
				{
					for (int k = 0; k < maxRequirements && Main.recipe[j].requiredItem[k].type != 0; k++)
					{
						if (Main.guideItem.IsTheSameAs(Main.recipe[j].requiredItem[k]))
						{
							Main.availableRecipe[Main.numAvailableRecipes] = j;
							Main.numAvailableRecipes++;
							break;
						}
					}
					continue;
				}
				for (int l = 0; l < maxRequirements && Main.recipe[j].requiredItem[l].type != 0; l++)
				{
					int num3 = Main.recipe[j].requiredItem[l].stack;
					for (int m = 0; m < 48; m++)
					{
						if (Main.player[Main.myPlayer].inventory[m].IsTheSameAs(Main.recipe[j].requiredItem[l]))
						{
							num3 -= Main.player[Main.myPlayer].inventory[m].stack;
						}
						if (num3 <= 0)
						{
							break;
						}
					}
					if (num3 > 0)
					{
						flag = false;
						break;
					}
				}
				if (!flag)
				{
					continue;
				}
				bool flag3 = true;
				for (int n = 0; n < maxRequirements && Main.recipe[j].requiredTile[n] != -1; n++)
				{
					if (!Main.player[Main.myPlayer].adjTile[Main.recipe[j].requiredTile[n]])
					{
						flag3 = false;
						break;
					}
				}
				if (flag3 && (!Main.recipe[j].needWater || Main.player[Main.myPlayer].adjWater) && (!Main.recipe[j].needLava || Main.player[Main.myPlayer].adjLava))
				{
					Main.availableRecipe[Main.numAvailableRecipes] = j;
					Main.numAvailableRecipes++;
				}
			}
			for (int num4 = 0; num4 < Main.numAvailableRecipes; num4++)
			{
				if (num == Main.availableRecipe[num4])
				{
					Main.focusRecipe = num4;
					break;
				}
			}
			if (Main.focusRecipe >= Main.numAvailableRecipes)
			{
				Main.focusRecipe = Main.numAvailableRecipes - 1;
			}
			if (Main.focusRecipe < 0)
			{
				Main.focusRecipe = 0;
			}
			float num5 = Main.availableRecipeY[Main.focusRecipe] - num2;
			for (int num6 = 0; num6 < maxRecipes; num6++)
			{
				Main.availableRecipeY[num6] -= num5;
			}
			Codable.RunGlobalMethod("ModGeneric", "OnRecipeRefresh");
		}

		public static void SetupRecipes()
		{
			newRecipe.createItem.SetDefaults("Mug");
			newRecipe.createItem.stack = 1;
			newRecipe.requiredItem[0].SetDefaults("Glass");
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults("Bowl of Soup");
			newRecipe.requiredItem[0].SetDefaults("Bowl");
			newRecipe.requiredItem[1].SetDefaults("Mushroom");
			newRecipe.requiredItem[2].SetDefaults("Goldfish");
			newRecipe.requiredTile[0] = 96;
			addRecipe();
			newRecipe.createItem.SetDefaults("Bottle");
			newRecipe.createItem.stack = 2;
			newRecipe.requiredItem[0].SetDefaults("Glass");
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults("Bottled Water");
			newRecipe.requiredItem[0].SetDefaults("Bottle");
			newRecipe.needWater = true;
			addRecipe();
			newRecipe.createItem.SetDefaults(422);
			newRecipe.createItem.stack = 5;
			newRecipe.requiredItem[0].SetDefaults("Bottled Water");
			newRecipe.requiredItem[1].SetDefaults(501);
			newRecipe.requiredItem[1].stack = 5;
			newRecipe.requiredItem[2].SetDefaults(369);
			addRecipe();
			newRecipe.createItem.SetDefaults(423);
			newRecipe.createItem.stack = 5;
			newRecipe.requiredItem[0].SetDefaults("Bottled Water");
			newRecipe.requiredItem[1].SetDefaults(370);
			newRecipe.requiredItem[2].SetDefaults(59);
			addRecipe();
			newRecipe.createItem.SetDefaults("Ale");
			newRecipe.requiredItem[0].SetDefaults(351);
			newRecipe.requiredTile[0] = 94;
			addRecipe();
			newRecipe.createItem.SetDefaults(28);
			newRecipe.createItem.stack = 2;
			newRecipe.requiredItem[0].SetDefaults(5);
			newRecipe.requiredItem[1].SetDefaults(23);
			newRecipe.requiredItem[1].stack = 2;
			newRecipe.requiredItem[2].SetDefaults(31);
			newRecipe.requiredItem[2].stack = 2;
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults("Healing Potion");
			newRecipe.requiredItem[0].SetDefaults(28);
			newRecipe.requiredItem[0].stack = 2;
			newRecipe.requiredItem[1].SetDefaults(183);
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults("Greater Healing Potion");
			newRecipe.createItem.stack = 1;
			newRecipe.requiredItem[0].SetDefaults(126);
			newRecipe.requiredItem[1].SetDefaults(501);
			newRecipe.requiredItem[1].stack = 3;
			newRecipe.requiredItem[2].SetDefaults(502);
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(110);
			newRecipe.createItem.stack = 2;
			newRecipe.requiredItem[0].SetDefaults(75);
			newRecipe.requiredItem[1].SetDefaults(23);
			newRecipe.requiredItem[1].stack = 2;
			newRecipe.requiredItem[2].SetDefaults(31);
			newRecipe.requiredItem[2].stack = 2;
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults("Mana Potion");
			newRecipe.requiredItem[0].SetDefaults(110);
			newRecipe.requiredItem[0].stack = 2;
			newRecipe.requiredItem[1].SetDefaults(183);
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(226);
			newRecipe.requiredItem[0].SetDefaults(28);
			newRecipe.requiredItem[1].SetDefaults(110);
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(227);
			newRecipe.requiredItem[0].SetDefaults("Healing Potion");
			newRecipe.requiredItem[1].SetDefaults("Mana Potion");
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(288);
			newRecipe.requiredItem[0].SetDefaults(126);
			newRecipe.requiredItem[1].SetDefaults(318);
			newRecipe.requiredItem[2].SetDefaults(317);
			newRecipe.requiredItem[3].SetDefaults("Obsidian");
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(289);
			newRecipe.requiredItem[0].SetDefaults(126);
			newRecipe.requiredItem[1].SetDefaults(313);
			newRecipe.requiredItem[2].SetDefaults("Mushroom");
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(290);
			newRecipe.requiredItem[0].SetDefaults(126);
			newRecipe.requiredItem[1].SetDefaults(315);
			newRecipe.requiredItem[2].SetDefaults("Cactus");
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(291);
			newRecipe.requiredItem[0].SetDefaults(126);
			newRecipe.requiredItem[1].SetDefaults(317);
			newRecipe.requiredItem[2].SetDefaults("Coral");
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(292);
			newRecipe.requiredItem[0].SetDefaults(126);
			newRecipe.requiredItem[1].SetDefaults(313);
			newRecipe.requiredItem[2].SetDefaults("Iron Ore");
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(293);
			newRecipe.requiredItem[0].SetDefaults(126);
			newRecipe.requiredItem[1].SetDefaults(314);
			newRecipe.requiredItem[2].SetDefaults(313);
			newRecipe.requiredItem[3].SetDefaults("Fallen Star");
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(294);
			newRecipe.requiredItem[0].SetDefaults(126);
			newRecipe.requiredItem[1].SetDefaults(314);
			newRecipe.requiredItem[2].SetDefaults(316);
			newRecipe.requiredItem[3].SetDefaults("Fallen Star");
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(295);
			newRecipe.requiredItem[0].SetDefaults(126);
			newRecipe.requiredItem[1].SetDefaults(313);
			newRecipe.requiredItem[2].SetDefaults(315);
			newRecipe.requiredItem[3].SetDefaults("Feather");
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(296);
			newRecipe.requiredItem[0].SetDefaults(126);
			newRecipe.requiredItem[1].SetDefaults(315);
			newRecipe.requiredItem[2].SetDefaults(314);
			newRecipe.requiredItem[3].SetDefaults("Gold Ore");
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(297);
			newRecipe.requiredItem[0].SetDefaults(126);
			newRecipe.requiredItem[1].SetDefaults(315);
			newRecipe.requiredItem[2].SetDefaults(314);
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(298);
			newRecipe.requiredItem[0].SetDefaults(126);
			newRecipe.requiredItem[1].SetDefaults(313);
			newRecipe.requiredItem[2].SetDefaults("Glowing Mushroom");
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(299);
			newRecipe.requiredItem[0].SetDefaults(126);
			newRecipe.requiredItem[1].SetDefaults(313);
			newRecipe.requiredItem[2].SetDefaults(315);
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(300);
			newRecipe.requiredItem[0].SetDefaults(126);
			newRecipe.requiredItem[1].SetDefaults(316);
			newRecipe.requiredItem[2].SetDefaults("Rotten Chunk");
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(301);
			newRecipe.requiredItem[0].SetDefaults(126);
			newRecipe.requiredItem[1].SetDefaults(316);
			newRecipe.requiredItem[2].SetDefaults("Cactus");
			newRecipe.requiredItem[3].SetDefaults("Worm Teeth");
			newRecipe.requiredItem[4].SetDefaults("Stinger");
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(302);
			newRecipe.requiredItem[0].SetDefaults(126);
			newRecipe.requiredItem[1].SetDefaults(317);
			newRecipe.requiredItem[2].SetDefaults(319);
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(303);
			newRecipe.requiredItem[0].SetDefaults(126);
			newRecipe.requiredItem[1].SetDefaults(313);
			newRecipe.requiredItem[2].SetDefaults("Lens");
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(304);
			newRecipe.requiredItem[0].SetDefaults(126);
			newRecipe.requiredItem[1].SetDefaults(313);
			newRecipe.requiredItem[2].SetDefaults(315);
			newRecipe.requiredItem[3].SetDefaults(319);
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(305);
			newRecipe.requiredItem[0].SetDefaults(126);
			newRecipe.requiredItem[1].SetDefaults(318);
			newRecipe.requiredItem[2].SetDefaults(316);
			newRecipe.requiredItem[3].SetDefaults(315);
			newRecipe.requiredItem[4].SetDefaults("Feather");
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(40);
			newRecipe.createItem.stack = 5;
			newRecipe.requiredItem[0].SetDefaults(9);
			newRecipe.requiredItem[1].SetDefaults(3);
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults("Flaming Arrow");
			newRecipe.createItem.stack = 3;
			newRecipe.requiredItem[0].SetDefaults(40);
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredItem[1].SetDefaults(8);
			addRecipe();
			newRecipe.createItem.SetDefaults("Unholy Arrow");
			newRecipe.createItem.stack = 3;
			newRecipe.requiredItem[0].SetDefaults(40);
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredItem[1].SetDefaults(69);
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Hellfire Arrow");
			newRecipe.createItem.stack = 10;
			newRecipe.requiredItem[0].SetDefaults(40);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredItem[1].SetDefaults(175);
			newRecipe.requiredItem[2].SetDefaults(8);
			newRecipe.requiredItem[2].stack = 5;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(545);
			newRecipe.createItem.stack = 15;
			newRecipe.requiredItem[0].SetDefaults(40);
			newRecipe.requiredItem[0].stack = 15;
			newRecipe.requiredItem[1].SetDefaults(522);
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(516);
			newRecipe.createItem.stack = 35;
			newRecipe.requiredItem[0].SetDefaults(40);
			newRecipe.requiredItem[0].stack = 35;
			newRecipe.requiredItem[1].SetDefaults(501);
			newRecipe.requiredItem[1].stack = 6;
			newRecipe.requiredItem[2].SetDefaults(526);
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults("Meteor Shot");
			newRecipe.createItem.stack = 25;
			newRecipe.requiredItem[0].SetDefaults("Musket Ball");
			newRecipe.requiredItem[0].stack = 25;
			newRecipe.requiredItem[1].SetDefaults(117);
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(515);
			newRecipe.createItem.stack = 25;
			newRecipe.requiredItem[0].SetDefaults("Musket Ball");
			newRecipe.requiredItem[0].stack = 25;
			newRecipe.requiredItem[1].SetDefaults(502);
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(546);
			newRecipe.createItem.stack = 25;
			newRecipe.requiredItem[0].SetDefaults("Musket Ball");
			newRecipe.requiredItem[0].stack = 25;
			newRecipe.requiredItem[1].SetDefaults(522);
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(255);
			newRecipe.requiredItem[0].SetDefaults(31);
			newRecipe.requiredItem[1].SetDefaults(195);
			newRecipe.requiredItem[1].stack = 3;
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(67);
			newRecipe.createItem.stack = 5;
			newRecipe.requiredItem[0].SetDefaults(60);
			newRecipe.requiredTile[0] = 13;
			addRecipe();
			newRecipe.createItem.SetDefaults(287);
			newRecipe.createItem.stack = 20;
			newRecipe.requiredItem[0].SetDefaults(279);
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredItem[1].SetDefaults(67);
			addRecipe();
			newRecipe.createItem.SetDefaults(8);
			newRecipe.createItem.stack = 3;
			newRecipe.requiredItem[0].SetDefaults(23);
			newRecipe.requiredItem[0].stack = 1;
			newRecipe.requiredItem[1].SetDefaults(9);
			addRecipe();
			newRecipe.createItem.SetDefaults(523);
			newRecipe.createItem.stack = 33;
			newRecipe.requiredItem[0].SetDefaults(8);
			newRecipe.requiredItem[0].stack = 33;
			newRecipe.requiredItem[1].SetDefaults(522);
			addRecipe();
			newRecipe.createItem.SetDefaults(427);
			newRecipe.createItem.stack = 3;
			newRecipe.requiredItem[0].SetDefaults(8);
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredItem[1].SetDefaults(177);
			addRecipe();
			newRecipe.createItem.SetDefaults(428);
			newRecipe.createItem.stack = 3;
			newRecipe.requiredItem[0].SetDefaults(8);
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredItem[1].SetDefaults(178);
			addRecipe();
			newRecipe.createItem.SetDefaults(429);
			newRecipe.createItem.stack = 3;
			newRecipe.requiredItem[0].SetDefaults(8);
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredItem[1].SetDefaults(179);
			addRecipe();
			newRecipe.createItem.SetDefaults(432);
			newRecipe.createItem.stack = 3;
			newRecipe.requiredItem[0].SetDefaults(8);
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredItem[1].SetDefaults(180);
			addRecipe();
			newRecipe.createItem.SetDefaults(430);
			newRecipe.createItem.stack = 3;
			newRecipe.requiredItem[0].SetDefaults(8);
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredItem[1].SetDefaults(181);
			addRecipe();
			newRecipe.createItem.SetDefaults(431);
			newRecipe.createItem.stack = 3;
			newRecipe.requiredItem[0].SetDefaults(8);
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredItem[1].SetDefaults(182);
			addRecipe();
			newRecipe.createItem.SetDefaults("Chinese Lantern");
			newRecipe.requiredItem[0].SetDefaults("Silk");
			newRecipe.requiredItem[0].stack = 5;
			newRecipe.requiredItem[1].SetDefaults("Torch");
			newRecipe.requiredItem[1].stack = 1;
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults("Tiki Torch");
			newRecipe.requiredItem[0].SetDefaults("Torch");
			newRecipe.requiredItem[1].SetDefaults("Wood");
			newRecipe.requiredItem[1].stack = 3;
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults("Lamp Post");
			newRecipe.requiredItem[0].SetDefaults("Iron Bar");
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredItem[1].SetDefaults("Glass");
			newRecipe.requiredItem[1].stack = 2;
			newRecipe.requiredItem[2].SetDefaults("Torch");
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Skull Lantern");
			newRecipe.createItem.stack = 1;
			newRecipe.requiredItem[0].SetDefaults("Bone");
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredItem[1].SetDefaults("Torch");
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(235);
			newRecipe.requiredItem[0].SetDefaults(166);
			newRecipe.requiredItem[1].SetDefaults(23);
			newRecipe.requiredItem[1].stack = 5;
			addRecipe();
			newRecipe.createItem.SetDefaults(286);
			newRecipe.requiredItem[0].SetDefaults(282);
			newRecipe.requiredItem[1].SetDefaults(23);
			addRecipe();
			newRecipe.createItem.SetDefaults("Glass");
			newRecipe.createItem.stack = 1;
			newRecipe.requiredItem[0].SetDefaults(169);
			newRecipe.requiredItem[0].stack = 2;
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults(392);
			newRecipe.createItem.stack = 4;
			newRecipe.requiredItem[0].SetDefaults("Glass");
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults("Clay Pot");
			newRecipe.requiredItem[0].SetDefaults(133);
			newRecipe.requiredItem[0].stack = 6;
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults("Pink Vase");
			newRecipe.requiredItem[0].SetDefaults("Clay Block");
			newRecipe.requiredItem[0].stack = 4;
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults("Bowl");
			newRecipe.requiredItem[0].SetDefaults("Clay Block");
			newRecipe.requiredItem[0].stack = 2;
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults("Gray Brick");
			newRecipe.requiredItem[0].SetDefaults(3);
			newRecipe.requiredItem[0].stack = 2;
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults("Gray Brick Wall");
			newRecipe.createItem.stack = 4;
			newRecipe.requiredItem[0].SetDefaults("Gray Brick");
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults("Red Brick");
			newRecipe.requiredItem[0].SetDefaults(133);
			newRecipe.requiredItem[0].stack = 2;
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults("Red Brick Wall");
			newRecipe.createItem.stack = 4;
			newRecipe.requiredItem[0].SetDefaults("Red Brick");
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults("Copper Brick");
			newRecipe.requiredItem[0].SetDefaults(3);
			newRecipe.requiredItem[0].stack = 1;
			newRecipe.requiredItem[1].SetDefaults("Copper Ore");
			newRecipe.requiredItem[1].stack = 1;
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults("Copper Brick Wall");
			newRecipe.createItem.stack = 4;
			newRecipe.requiredItem[0].SetDefaults("Copper Brick");
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults("Silver Brick Wall");
			newRecipe.createItem.stack = 4;
			newRecipe.requiredItem[0].SetDefaults("Silver Brick");
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults("Silver Brick");
			newRecipe.requiredItem[0].SetDefaults(3);
			newRecipe.requiredItem[0].stack = 1;
			newRecipe.requiredItem[1].SetDefaults("Silver Ore");
			newRecipe.requiredItem[1].stack = 1;
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults("Gold Brick Wall");
			newRecipe.createItem.stack = 4;
			newRecipe.requiredItem[0].SetDefaults("Gold Brick");
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults("Gold Brick");
			newRecipe.requiredItem[0].SetDefaults(3);
			newRecipe.requiredItem[0].stack = 1;
			newRecipe.requiredItem[1].SetDefaults("Gold Ore");
			newRecipe.requiredItem[1].stack = 1;
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults("Hellstone Brick");
			newRecipe.requiredItem[0].SetDefaults(174);
			newRecipe.requiredItem[1].SetDefaults(3);
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults(192);
			newRecipe.requiredItem[0].SetDefaults(173);
			newRecipe.requiredItem[0].stack = 2;
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults(330);
			newRecipe.createItem.stack = 4;
			newRecipe.requiredItem[0].SetDefaults(192);
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults(594);
			newRecipe.requiredItem[0].SetDefaults(593);
			newRecipe.requiredItem[0].stack = 2;
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(595);
			newRecipe.createItem.stack = 4;
			newRecipe.requiredItem[0].SetDefaults(594);
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(587);
			newRecipe.createItem.stack = 4;
			newRecipe.requiredItem[0].SetDefaults(586);
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(592);
			newRecipe.createItem.stack = 4;
			newRecipe.requiredItem[0].SetDefaults(591);
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(412);
			newRecipe.requiredItem[0].SetDefaults(408);
			newRecipe.requiredItem[1].SetDefaults(409);
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults(417);
			newRecipe.createItem.stack = 4;
			newRecipe.requiredItem[0].SetDefaults(412);
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(413);
			newRecipe.requiredItem[0].SetDefaults(3);
			newRecipe.requiredItem[1].SetDefaults(172);
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults(418);
			newRecipe.createItem.stack = 4;
			newRecipe.requiredItem[0].SetDefaults(413);
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(414);
			newRecipe.requiredItem[0].SetDefaults(3);
			newRecipe.requiredItem[1].SetDefaults(176);
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults(419);
			newRecipe.createItem.stack = 4;
			newRecipe.requiredItem[0].SetDefaults(414);
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(415);
			newRecipe.requiredItem[0].SetDefaults(3);
			newRecipe.requiredItem[1].SetDefaults(364);
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults(420);
			newRecipe.createItem.stack = 4;
			newRecipe.requiredItem[0].SetDefaults(415);
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(416);
			newRecipe.requiredItem[0].SetDefaults(3);
			newRecipe.requiredItem[1].SetDefaults(365);
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults(421);
			newRecipe.createItem.stack = 4;
			newRecipe.requiredItem[0].SetDefaults(416);
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(577);
			newRecipe.createItem.stack = 5;
			newRecipe.requiredItem[0].SetDefaults(56);
			newRecipe.requiredItem[1].SetDefaults(61);
			newRecipe.requiredItem[1].stack = 5;
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults(176);
			newRecipe.requiredItem[0].SetDefaults(2);
			newRecipe.needWater = true;
			addRecipe();
			newRecipe.createItem.SetDefaults(30);
			newRecipe.createItem.stack = 4;
			newRecipe.requiredItem[0].SetDefaults(2);
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(26);
			newRecipe.createItem.stack = 4;
			newRecipe.requiredItem[0].SetDefaults(3);
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(93);
			newRecipe.createItem.stack = 4;
			newRecipe.requiredItem[0].SetDefaults(9);
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(94);
			newRecipe.requiredItem[0].SetDefaults(9);
			addRecipe();
			newRecipe.createItem.SetDefaults(25);
			newRecipe.requiredItem[0].SetDefaults(9);
			newRecipe.requiredItem[0].stack = 6;
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(34);
			newRecipe.requiredItem[0].SetDefaults(9);
			newRecipe.requiredItem[0].stack = 4;
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults("Sign");
			newRecipe.requiredItem[0].SetDefaults(9);
			newRecipe.requiredItem[0].stack = 6;
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(48);
			newRecipe.requiredItem[0].SetDefaults(9);
			newRecipe.requiredItem[0].stack = 8;
			newRecipe.requiredItem[1].SetDefaults(22);
			newRecipe.requiredItem[1].stack = 2;
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(32);
			newRecipe.requiredItem[0].SetDefaults(9);
			newRecipe.requiredItem[0].stack = 8;
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(36);
			newRecipe.requiredItem[0].SetDefaults(9);
			newRecipe.requiredItem[0].stack = 10;
			addRecipe();
			newRecipe.createItem.SetDefaults(479);
			newRecipe.createItem.stack = 4;
			newRecipe.requiredItem[0].SetDefaults(3);
			newRecipe.requiredItem[0].stack = 1;
			newRecipe.requiredItem[1].SetDefaults(9);
			newRecipe.requiredItem[1].stack = 1;
			newRecipe.requiredTile[0] = 106;
			addRecipe();
			newRecipe.createItem.SetDefaults(480);
			newRecipe.createItem.stack = 2;
			newRecipe.requiredItem[0].SetDefaults(9);
			newRecipe.requiredItem[0].stack = 1;
			newRecipe.requiredTile[0] = 106;
			addRecipe();
			newRecipe.createItem.SetDefaults(498);
			newRecipe.requiredItem[0].SetDefaults(9);
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredTile[0] = 106;
			addRecipe();
			newRecipe.createItem.SetDefaults("Bed");
			newRecipe.requiredItem[0].SetDefaults(9);
			newRecipe.requiredItem[0].stack = 15;
			newRecipe.requiredItem[1].SetDefaults("Silk");
			newRecipe.requiredItem[1].stack = 5;
			newRecipe.requiredTile[0] = 106;
			addRecipe();
			newRecipe.createItem.SetDefaults("Bookcase");
			newRecipe.createItem.stack = 1;
			newRecipe.requiredItem[0].SetDefaults("Wood");
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredItem[1].SetDefaults("Book");
			newRecipe.requiredItem[1].stack = 10;
			newRecipe.requiredTile[0] = 106;
			addRecipe();
			newRecipe.createItem.SetDefaults("Barrel");
			newRecipe.requiredItem[0].SetDefaults(9);
			newRecipe.requiredItem[0].stack = 9;
			newRecipe.requiredItem[1].SetDefaults(22);
			newRecipe.requiredItem[1].stack = 1;
			newRecipe.requiredTile[0] = 106;
			addRecipe();
			newRecipe.createItem.SetDefaults("Grandfather Clock");
			newRecipe.requiredItem[0].SetDefaults("Gold Bar");
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredItem[1].SetDefaults("Glass");
			newRecipe.requiredItem[1].stack = 6;
			newRecipe.requiredItem[2].SetDefaults("Wood");
			newRecipe.requiredItem[2].stack = 10;
			newRecipe.requiredTile[0] = 106;
			addRecipe();
			newRecipe.createItem.SetDefaults("Keg");
			newRecipe.requiredItem[0].SetDefaults("Wood");
			newRecipe.requiredItem[0].stack = 14;
			newRecipe.requiredTile[0] = 106;
			addRecipe();
			newRecipe.createItem.SetDefaults("Piano");
			newRecipe.requiredItem[0].SetDefaults("Bone");
			newRecipe.requiredItem[0].stack = 4;
			newRecipe.requiredItem[1].SetDefaults("Wood");
			newRecipe.requiredItem[1].stack = 15;
			newRecipe.requiredItem[2].SetDefaults("Book");
			newRecipe.requiredTile[0] = 106;
			addRecipe();
			newRecipe.createItem.SetDefaults("Loom");
			newRecipe.requiredItem[0].SetDefaults("Wood");
			newRecipe.requiredItem[0].stack = 12;
			newRecipe.requiredTile[0] = 106;
			addRecipe();
			newRecipe.createItem.SetDefaults("Dresser");
			newRecipe.requiredItem[0].SetDefaults("Wood");
			newRecipe.requiredItem[0].stack = 16;
			newRecipe.requiredTile[0] = 106;
			addRecipe();
			newRecipe.createItem.SetDefaults("Bench");
			newRecipe.requiredItem[0].SetDefaults("Wood");
			newRecipe.requiredItem[0].stack = 8;
			newRecipe.requiredTile[0] = 106;
			addRecipe();
			newRecipe.createItem.SetDefaults("Sawmill");
			newRecipe.requiredItem[0].SetDefaults("Wood");
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredItem[1].SetDefaults("Iron Bar");
			newRecipe.requiredItem[1].stack = 2;
			newRecipe.requiredItem[2].SetDefaults("Iron Chain");
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(24);
			newRecipe.requiredItem[0].SetDefaults(9);
			newRecipe.requiredItem[0].stack = 7;
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(196);
			newRecipe.requiredItem[0].SetDefaults(9);
			newRecipe.requiredItem[0].stack = 8;
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(39);
			newRecipe.requiredItem[0].SetDefaults(9);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(361);
			newRecipe.requiredItem[0].SetDefaults(362);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredItem[1].SetDefaults("Wood");
			newRecipe.requiredItem[1].stack = 5;
			newRecipe.requiredTile[0] = 86;
			addRecipe();
			newRecipe.createItem.SetDefaults("Silk");
			newRecipe.requiredItem[0].SetDefaults(150);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredTile[0] = 86;
			addRecipe();
			newRecipe.createItem.SetDefaults("Red Banner");
			newRecipe.requiredItem[0].SetDefaults("Silk");
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredTile[0] = 86;
			addRecipe();
			newRecipe.createItem.SetDefaults("Green Banner");
			newRecipe.requiredItem[0].SetDefaults("Silk");
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredTile[0] = 86;
			addRecipe();
			newRecipe.createItem.SetDefaults("Blue Banner");
			newRecipe.requiredItem[0].SetDefaults("Silk");
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredTile[0] = 86;
			addRecipe();
			newRecipe.createItem.SetDefaults("Yellow Banner");
			newRecipe.requiredItem[0].SetDefaults("Silk");
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredTile[0] = 86;
			addRecipe();
			newRecipe.createItem.SetDefaults(247);
			newRecipe.requiredItem[0].SetDefaults("Silk");
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredItem[1].SetDefaults(255);
			newRecipe.requiredItem[1].stack = 3;
			newRecipe.requiredTile[0] = 86;
			addRecipe();
			newRecipe.createItem.SetDefaults(248);
			newRecipe.requiredItem[0].SetDefaults("Silk");
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredItem[1].SetDefaults(255);
			newRecipe.requiredItem[1].stack = 3;
			newRecipe.requiredTile[0] = 86;
			addRecipe();
			newRecipe.createItem.SetDefaults(249);
			newRecipe.requiredItem[0].SetDefaults("Silk");
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredItem[1].SetDefaults(255);
			newRecipe.requiredItem[1].stack = 3;
			newRecipe.requiredTile[0] = 86;
			addRecipe();
			newRecipe.createItem.SetDefaults(240);
			newRecipe.requiredItem[0].SetDefaults("Silk");
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredItem[1].SetDefaults(254);
			newRecipe.requiredItem[1].stack = 3;
			newRecipe.requiredTile[0] = 86;
			addRecipe();
			newRecipe.createItem.SetDefaults(241);
			newRecipe.requiredItem[0].SetDefaults("Silk");
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredItem[1].SetDefaults(254);
			newRecipe.requiredItem[1].stack = 3;
			newRecipe.requiredTile[0] = 86;
			addRecipe();
			newRecipe.createItem.SetDefaults(262);
			newRecipe.requiredItem[0].SetDefaults("Silk");
			newRecipe.requiredItem[0].stack = 30;
			newRecipe.requiredItem[1].SetDefaults(178);
			newRecipe.requiredItem[1].stack = 3;
			newRecipe.requiredTile[0] = 86;
			addRecipe();
			newRecipe.createItem.SetDefaults(259);
			newRecipe.requiredItem[0].SetDefaults(68);
			newRecipe.requiredItem[0].stack = 5;
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(252);
			newRecipe.requiredItem[0].SetDefaults(259);
			newRecipe.requiredItem[0].stack = 15;
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(253);
			newRecipe.requiredItem[0].SetDefaults(259);
			newRecipe.requiredItem[0].stack = 15;
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(250);
			newRecipe.requiredItem[0].SetDefaults(261);
			newRecipe.requiredItem[0].stack = 2;
			newRecipe.requiredItem[1].SetDefaults("Bottled Water");
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(33);
			newRecipe.requiredItem[0].SetDefaults(3);
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredItem[1].SetDefaults(9);
			newRecipe.requiredItem[1].stack = 4;
			newRecipe.requiredItem[2].SetDefaults(8);
			newRecipe.requiredItem[2].stack = 3;
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(360);
			newRecipe.requiredItem[0].SetDefaults("Stone Block");
			newRecipe.requiredItem[0].stack = 100;
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(20);
			newRecipe.requiredItem[0].SetDefaults(12);
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults("Copper Pickaxe");
			newRecipe.requiredItem[0].SetDefaults(20);
			newRecipe.requiredItem[0].stack = 12;
			newRecipe.requiredItem[1].SetDefaults(9);
			newRecipe.requiredItem[1].stack = 4;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Copper Axe");
			newRecipe.requiredItem[0].SetDefaults(20);
			newRecipe.requiredItem[0].stack = 9;
			newRecipe.requiredItem[1].SetDefaults(9);
			newRecipe.requiredItem[1].stack = 3;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Copper Hammer");
			newRecipe.requiredItem[0].SetDefaults(20);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredItem[1].SetDefaults(9);
			newRecipe.requiredItem[1].stack = 3;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Copper Broadsword");
			newRecipe.requiredItem[0].SetDefaults(20);
			newRecipe.requiredItem[0].stack = 8;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Copper Shortsword");
			newRecipe.requiredItem[0].SetDefaults(20);
			newRecipe.requiredItem[0].stack = 7;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Copper Bow");
			newRecipe.requiredItem[0].SetDefaults(20);
			newRecipe.requiredItem[0].stack = 7;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Copper Helmet");
			newRecipe.requiredItem[0].SetDefaults(20);
			newRecipe.requiredItem[0].stack = 15;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Copper Chainmail");
			newRecipe.requiredItem[0].SetDefaults(20);
			newRecipe.requiredItem[0].stack = 25;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Copper Greaves");
			newRecipe.requiredItem[0].SetDefaults(20);
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Copper Watch");
			newRecipe.requiredItem[0].SetDefaults(20);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredItem[1].SetDefaults(85);
			newRecipe.requiredTile[0] = 14;
			newRecipe.requiredTile[1] = 15;
			addRecipe();
			newRecipe.createItem.SetDefaults("Copper Chandelier");
			newRecipe.requiredItem[0].SetDefaults(20);
			newRecipe.requiredItem[0].stack = 4;
			newRecipe.requiredItem[1].SetDefaults(8);
			newRecipe.requiredItem[1].stack = 4;
			newRecipe.requiredItem[2].SetDefaults(85);
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(22);
			newRecipe.requiredItem[0].SetDefaults(11);
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults(35);
			newRecipe.requiredItem[0].SetDefaults(22);
			newRecipe.requiredItem[0].stack = 5;
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(205);
			newRecipe.requiredItem[0].SetDefaults(22);
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Trash Can");
			newRecipe.requiredItem[0].SetDefaults(22);
			newRecipe.requiredItem[0].stack = 8;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Bathtub");
			newRecipe.requiredItem[0].SetDefaults(22);
			newRecipe.requiredItem[0].stack = 14;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Toilet");
			newRecipe.requiredItem[0].SetDefaults(22);
			newRecipe.requiredItem[0].stack = 6;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Cooking Pot");
			newRecipe.requiredItem[0].SetDefaults("Iron Bar");
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredItem[1].SetDefaults("Wood");
			newRecipe.requiredItem[1].stack = 2;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(1);
			newRecipe.requiredItem[0].SetDefaults(22);
			newRecipe.requiredItem[0].stack = 12;
			newRecipe.requiredItem[1].SetDefaults(9);
			newRecipe.requiredItem[1].stack = 3;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(10);
			newRecipe.requiredItem[0].SetDefaults(22);
			newRecipe.requiredItem[0].stack = 9;
			newRecipe.requiredItem[1].SetDefaults(9);
			newRecipe.requiredItem[1].stack = 3;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(7);
			newRecipe.requiredItem[0].SetDefaults(22);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredItem[1].SetDefaults(9);
			newRecipe.requiredItem[1].stack = 3;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(4);
			newRecipe.requiredItem[0].SetDefaults(22);
			newRecipe.requiredItem[0].stack = 8;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(6);
			newRecipe.requiredItem[0].SetDefaults(22);
			newRecipe.requiredItem[0].stack = 7;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Iron Bow");
			newRecipe.requiredItem[0].SetDefaults(22);
			newRecipe.requiredItem[0].stack = 7;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Iron Helmet");
			newRecipe.requiredItem[0].SetDefaults(22);
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Iron Chainmail");
			newRecipe.requiredItem[0].SetDefaults(22);
			newRecipe.requiredItem[0].stack = 30;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Iron Greaves");
			newRecipe.requiredItem[0].SetDefaults(22);
			newRecipe.requiredItem[0].stack = 25;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Iron Chain");
			newRecipe.requiredItem[0].SetDefaults(22);
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(21);
			newRecipe.requiredItem[0].SetDefaults(14);
			newRecipe.requiredItem[0].stack = 4;
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults("Silver Pickaxe");
			newRecipe.requiredItem[0].SetDefaults(21);
			newRecipe.requiredItem[0].stack = 12;
			newRecipe.requiredItem[1].SetDefaults(9);
			newRecipe.requiredItem[1].stack = 4;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Silver Axe");
			newRecipe.requiredItem[0].SetDefaults(21);
			newRecipe.requiredItem[0].stack = 9;
			newRecipe.requiredItem[1].SetDefaults(9);
			newRecipe.requiredItem[1].stack = 3;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Silver Hammer");
			newRecipe.requiredItem[0].SetDefaults(21);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredItem[1].SetDefaults(9);
			newRecipe.requiredItem[1].stack = 3;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Silver Broadsword");
			newRecipe.requiredItem[0].SetDefaults(21);
			newRecipe.requiredItem[0].stack = 8;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Silver Shortsword");
			newRecipe.requiredItem[0].SetDefaults(21);
			newRecipe.requiredItem[0].stack = 6;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Silver Bow");
			newRecipe.requiredItem[0].SetDefaults(21);
			newRecipe.requiredItem[0].stack = 7;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Silver Helmet");
			newRecipe.requiredItem[0].SetDefaults(21);
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Silver Chainmail");
			newRecipe.requiredItem[0].SetDefaults(21);
			newRecipe.requiredItem[0].stack = 30;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Silver Greaves");
			newRecipe.requiredItem[0].SetDefaults(21);
			newRecipe.requiredItem[0].stack = 25;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Silver Watch");
			newRecipe.requiredItem[0].SetDefaults(21);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredItem[1].SetDefaults(85);
			newRecipe.requiredTile[0] = 14;
			newRecipe.requiredTile[1] = 15;
			addRecipe();
			newRecipe.createItem.SetDefaults("Silver Chandelier");
			newRecipe.requiredItem[0].SetDefaults(21);
			newRecipe.requiredItem[0].stack = 4;
			newRecipe.requiredItem[1].SetDefaults(8);
			newRecipe.requiredItem[1].stack = 4;
			newRecipe.requiredItem[2].SetDefaults(85);
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(19);
			newRecipe.requiredItem[0].SetDefaults(13);
			newRecipe.requiredItem[0].stack = 4;
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults("Gold Pickaxe");
			newRecipe.requiredItem[0].SetDefaults(19);
			newRecipe.requiredItem[0].stack = 12;
			newRecipe.requiredItem[1].SetDefaults(9);
			newRecipe.requiredItem[1].stack = 4;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Gold Axe");
			newRecipe.requiredItem[0].SetDefaults(19);
			newRecipe.requiredItem[0].stack = 9;
			newRecipe.requiredItem[1].SetDefaults(9);
			newRecipe.requiredItem[1].stack = 3;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Gold Hammer");
			newRecipe.requiredItem[0].SetDefaults(19);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredItem[1].SetDefaults(9);
			newRecipe.requiredItem[1].stack = 3;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Gold Broadsword");
			newRecipe.requiredItem[0].SetDefaults(19);
			newRecipe.requiredItem[0].stack = 8;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Gold Shortsword");
			newRecipe.requiredItem[0].SetDefaults(19);
			newRecipe.requiredItem[0].stack = 7;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Gold Bow");
			newRecipe.requiredItem[0].SetDefaults(19);
			newRecipe.requiredItem[0].stack = 7;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Gold Helmet");
			newRecipe.requiredItem[0].SetDefaults(19);
			newRecipe.requiredItem[0].stack = 25;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Gold Chainmail");
			newRecipe.requiredItem[0].SetDefaults(19);
			newRecipe.requiredItem[0].stack = 35;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Gold Greaves");
			newRecipe.requiredItem[0].SetDefaults(19);
			newRecipe.requiredItem[0].stack = 30;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Gold Watch");
			newRecipe.requiredItem[0].SetDefaults(19);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredItem[1].SetDefaults(85);
			newRecipe.requiredTile[0] = 14;
			newRecipe.requiredTile[1] = 15;
			addRecipe();
			newRecipe.createItem.SetDefaults("Gold Crown");
			newRecipe.requiredItem[0].SetDefaults(19);
			newRecipe.requiredItem[0].stack = 30;
			newRecipe.requiredItem[1].SetDefaults("Ruby");
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Gold Chandelier");
			newRecipe.requiredItem[0].SetDefaults(19);
			newRecipe.requiredItem[0].stack = 4;
			newRecipe.requiredItem[1].SetDefaults(8);
			newRecipe.requiredItem[1].stack = 4;
			newRecipe.requiredItem[2].SetDefaults(85);
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Throne");
			newRecipe.requiredItem[0].SetDefaults("Silk");
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredItem[1].SetDefaults("Gold Bar");
			newRecipe.requiredItem[1].stack = 30;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Candle");
			newRecipe.requiredItem[0].SetDefaults(19);
			newRecipe.requiredItem[1].SetDefaults(8);
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults("Candelabra");
			newRecipe.createItem.stack = 1;
			newRecipe.requiredItem[0].SetDefaults("Gold Bar");
			newRecipe.requiredItem[0].stack = 5;
			newRecipe.requiredItem[1].SetDefaults("Torch");
			newRecipe.requiredItem[1].stack = 3;
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(57);
			newRecipe.requiredItem[0].SetDefaults(56);
			newRecipe.requiredItem[0].stack = 4;
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults(44);
			newRecipe.requiredItem[0].SetDefaults(57);
			newRecipe.requiredItem[0].stack = 8;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(45);
			newRecipe.requiredItem[0].SetDefaults(57);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(46);
			newRecipe.requiredItem[0].SetDefaults(57);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Shadow Helmet");
			newRecipe.requiredItem[0].SetDefaults(57);
			newRecipe.requiredItem[0].stack = 15;
			newRecipe.requiredItem[1].SetDefaults(86);
			newRecipe.requiredItem[1].stack = 10;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Shadow Scalemail");
			newRecipe.requiredItem[0].SetDefaults(57);
			newRecipe.requiredItem[0].stack = 25;
			newRecipe.requiredItem[1].SetDefaults(86);
			newRecipe.requiredItem[1].stack = 20;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Shadow Greaves");
			newRecipe.requiredItem[0].SetDefaults(57);
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredItem[1].SetDefaults(86);
			newRecipe.requiredItem[1].stack = 15;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Nightmare Pickaxe");
			newRecipe.requiredItem[0].SetDefaults(57);
			newRecipe.requiredItem[0].stack = 12;
			newRecipe.requiredItem[1].SetDefaults(86);
			newRecipe.requiredItem[1].stack = 6;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("The Breaker");
			newRecipe.requiredItem[0].SetDefaults(57);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredItem[1].SetDefaults(86);
			newRecipe.requiredItem[1].stack = 5;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Grappling Hook");
			newRecipe.requiredItem[0].SetDefaults(85);
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredItem[1].SetDefaults(118);
			newRecipe.requiredItem[1].stack = 1;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(117);
			newRecipe.requiredItem[0].SetDefaults(116);
			newRecipe.requiredItem[0].stack = 4;
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults(198);
			newRecipe.requiredItem[0].SetDefaults(117);
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredItem[1].SetDefaults(177);
			newRecipe.requiredItem[1].stack = 10;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(199);
			newRecipe.requiredItem[0].SetDefaults(117);
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredItem[1].SetDefaults(178);
			newRecipe.requiredItem[1].stack = 10;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(200);
			newRecipe.requiredItem[0].SetDefaults(117);
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredItem[1].SetDefaults(179);
			newRecipe.requiredItem[1].stack = 10;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(201);
			newRecipe.requiredItem[0].SetDefaults(117);
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredItem[1].SetDefaults(181);
			newRecipe.requiredItem[1].stack = 10;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(202);
			newRecipe.requiredItem[0].SetDefaults(117);
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredItem[1].SetDefaults(182);
			newRecipe.requiredItem[1].stack = 10;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(203);
			newRecipe.requiredItem[0].SetDefaults(117);
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredItem[1].SetDefaults(180);
			newRecipe.requiredItem[1].stack = 10;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Blue Phasesaber");
			newRecipe.requiredItem[0].SetDefaults(198);
			newRecipe.requiredItem[1].SetDefaults(502);
			newRecipe.requiredItem[1].stack = 50;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Red Phasesaber");
			newRecipe.requiredItem[0].SetDefaults(199);
			newRecipe.requiredItem[1].SetDefaults(502);
			newRecipe.requiredItem[1].stack = 50;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Green Phasesaber");
			newRecipe.requiredItem[0].SetDefaults(200);
			newRecipe.requiredItem[1].SetDefaults(502);
			newRecipe.requiredItem[1].stack = 50;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Purple Phasesaber");
			newRecipe.requiredItem[0].SetDefaults(201);
			newRecipe.requiredItem[1].SetDefaults(502);
			newRecipe.requiredItem[1].stack = 50;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("White Phasesaber");
			newRecipe.requiredItem[0].SetDefaults(202);
			newRecipe.requiredItem[1].SetDefaults(502);
			newRecipe.requiredItem[1].stack = 50;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Yellow Phasesaber");
			newRecipe.requiredItem[0].SetDefaults(203);
			newRecipe.requiredItem[1].SetDefaults(502);
			newRecipe.requiredItem[1].stack = 50;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(204);
			newRecipe.requiredItem[0].SetDefaults(117);
			newRecipe.requiredItem[0].stack = 35;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(127);
			newRecipe.requiredItem[0].SetDefaults(95);
			newRecipe.requiredItem[1].SetDefaults(117);
			newRecipe.requiredItem[1].stack = 30;
			newRecipe.requiredItem[2].SetDefaults(75);
			newRecipe.requiredItem[2].stack = 10;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(197);
			newRecipe.requiredItem[0].SetDefaults(98);
			newRecipe.requiredItem[1].SetDefaults(117);
			newRecipe.requiredItem[1].stack = 20;
			newRecipe.requiredItem[2].SetDefaults(75);
			newRecipe.requiredItem[2].stack = 5;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Meteor Helmet");
			newRecipe.requiredItem[0].SetDefaults(117);
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Meteor Suit");
			newRecipe.requiredItem[0].SetDefaults(117);
			newRecipe.requiredItem[0].stack = 30;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Meteor Leggings");
			newRecipe.requiredItem[0].SetDefaults(117);
			newRecipe.requiredItem[0].stack = 25;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(151);
			newRecipe.requiredItem[0].SetDefaults(154);
			newRecipe.requiredItem[0].stack = 40;
			newRecipe.requiredItem[1].SetDefaults(150);
			newRecipe.requiredItem[1].stack = 40;
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(152);
			newRecipe.requiredItem[0].SetDefaults(154);
			newRecipe.requiredItem[0].stack = 60;
			newRecipe.requiredItem[1].SetDefaults(150);
			newRecipe.requiredItem[1].stack = 50;
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(153);
			newRecipe.requiredItem[0].SetDefaults(154);
			newRecipe.requiredItem[0].stack = 50;
			newRecipe.requiredItem[1].SetDefaults(150);
			newRecipe.requiredItem[1].stack = 45;
			newRecipe.requiredTile[0] = 18;
			addRecipe();
			newRecipe.createItem.SetDefaults(190);
			newRecipe.requiredItem[0].SetDefaults(331);
			newRecipe.requiredItem[0].stack = 12;
			newRecipe.requiredItem[1].SetDefaults(209);
			newRecipe.requiredItem[1].stack = 15;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(191);
			newRecipe.requiredItem[0].SetDefaults(331);
			newRecipe.requiredItem[0].stack = 6;
			newRecipe.requiredItem[1].SetDefaults(209);
			newRecipe.requiredItem[1].stack = 15;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(185);
			newRecipe.requiredItem[0].SetDefaults(84);
			newRecipe.requiredItem[1].SetDefaults(331);
			newRecipe.requiredItem[1].stack = 12;
			newRecipe.requiredItem[2].SetDefaults(210);
			newRecipe.requiredItem[2].stack = 3;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(228);
			newRecipe.requiredItem[0].SetDefaults(179);
			newRecipe.requiredItem[0].stack = 1;
			newRecipe.requiredItem[1].SetDefaults(177);
			newRecipe.requiredItem[1].stack = 1;
			newRecipe.requiredItem[2].SetDefaults(331);
			newRecipe.requiredItem[2].stack = 8;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(229);
			newRecipe.requiredItem[0].SetDefaults(178);
			newRecipe.requiredItem[0].stack = 1;
			newRecipe.requiredItem[1].SetDefaults(182);
			newRecipe.requiredItem[1].stack = 1;
			newRecipe.requiredItem[2].SetDefaults(331);
			newRecipe.requiredItem[2].stack = 16;
			newRecipe.requiredItem[3].SetDefaults(209);
			newRecipe.requiredItem[3].stack = 12;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(230);
			newRecipe.requiredItem[0].SetDefaults(181);
			newRecipe.requiredItem[0].stack = 1;
			newRecipe.requiredItem[1].SetDefaults(180);
			newRecipe.requiredItem[1].stack = 1;
			newRecipe.requiredItem[2].SetDefaults(331);
			newRecipe.requiredItem[2].stack = 8;
			newRecipe.requiredItem[3].SetDefaults(210);
			newRecipe.requiredItem[3].stack = 2;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(175);
			newRecipe.requiredItem[0].SetDefaults(174);
			newRecipe.requiredItem[0].stack = 4;
			newRecipe.requiredItem[1].SetDefaults(173);
			newRecipe.requiredItem[1].stack = 1;
			newRecipe.requiredTile[0] = 77;
			addRecipe();
			newRecipe.createItem.SetDefaults(119);
			newRecipe.requiredItem[0].SetDefaults(175);
			newRecipe.requiredItem[0].stack = 15;
			newRecipe.requiredItem[1].SetDefaults(55);
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(120);
			newRecipe.requiredItem[0].SetDefaults(175);
			newRecipe.requiredItem[0].stack = 25;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(121);
			newRecipe.requiredItem[0].SetDefaults(175);
			newRecipe.requiredItem[0].stack = 35;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(122);
			newRecipe.requiredItem[0].SetDefaults(175);
			newRecipe.requiredItem[0].stack = 35;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(217);
			newRecipe.requiredItem[0].SetDefaults(175);
			newRecipe.requiredItem[0].stack = 35;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(219);
			newRecipe.requiredItem[0].SetDefaults(175);
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredItem[1].SetDefaults("Handgun");
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(231);
			newRecipe.requiredItem[0].SetDefaults(175);
			newRecipe.requiredItem[0].stack = 25;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(232);
			newRecipe.requiredItem[0].SetDefaults(175);
			newRecipe.requiredItem[0].stack = 35;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(233);
			newRecipe.requiredItem[0].SetDefaults(175);
			newRecipe.requiredItem[0].stack = 30;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(273);
			newRecipe.requiredItem[0].SetDefaults(46);
			newRecipe.requiredItem[1].SetDefaults(155);
			newRecipe.requiredItem[2].SetDefaults(190);
			newRecipe.requiredItem[3].SetDefaults(121);
			newRecipe.requiredTile[0] = 26;
			addRecipe();
			newRecipe.createItem.SetDefaults(389);
			newRecipe.requiredItem[0].SetDefaults(527);
			newRecipe.requiredItem[1].SetDefaults(528);
			newRecipe.requiredItem[2].SetDefaults(521);
			newRecipe.requiredItem[2].stack = 10;
			newRecipe.requiredItem[3].SetDefaults(520);
			newRecipe.requiredItem[3].stack = 10;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(381);
			newRecipe.requiredItem[0].SetDefaults(364);
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults("Cobalt Helmet");
			newRecipe.requiredItem[0].SetDefaults(381);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Cobalt Mask");
			newRecipe.requiredItem[0].SetDefaults(381);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Cobalt Hat");
			newRecipe.requiredItem[0].SetDefaults(381);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Cobalt Breastplate");
			newRecipe.requiredItem[0].SetDefaults(381);
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Cobalt Leggings");
			newRecipe.requiredItem[0].SetDefaults(381);
			newRecipe.requiredItem[0].stack = 15;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Cobalt Drill");
			newRecipe.requiredItem[0].SetDefaults(381);
			newRecipe.requiredItem[0].stack = 15;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Cobalt Chainsaw");
			newRecipe.requiredItem[0].SetDefaults(381);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Cobalt Repeater");
			newRecipe.requiredItem[0].SetDefaults(381);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults("Cobalt Sword");
			newRecipe.requiredItem[0].SetDefaults(381);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(537);
			newRecipe.requiredItem[0].SetDefaults(381);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(382);
			newRecipe.requiredItem[0].SetDefaults(365);
			newRecipe.requiredItem[0].stack = 4;
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults("Mythril Helmet");
			newRecipe.requiredItem[0].SetDefaults(382);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults("Mythril Hat");
			newRecipe.requiredItem[0].SetDefaults(382);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults("Mythril Hood");
			newRecipe.requiredItem[0].SetDefaults(382);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults("Mythril Chainmail");
			newRecipe.requiredItem[0].SetDefaults(382);
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults("Mythril Greaves");
			newRecipe.requiredItem[0].SetDefaults(382);
			newRecipe.requiredItem[0].stack = 15;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults("Mythril Drill");
			newRecipe.requiredItem[0].SetDefaults(382);
			newRecipe.requiredItem[0].stack = 15;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults("Mythril Chainsaw");
			newRecipe.requiredItem[0].SetDefaults(382);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults("Mythril Repeater");
			newRecipe.requiredItem[0].SetDefaults(382);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults("Mythril Sword");
			newRecipe.requiredItem[0].SetDefaults(382);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults("Mythril Halberd");
			newRecipe.requiredItem[0].SetDefaults(382);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(525);
			newRecipe.requiredItem[0].SetDefaults(382);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(391);
			newRecipe.requiredItem[0].SetDefaults(366);
			newRecipe.requiredItem[0].stack = 5;
			newRecipe.requiredTile[0] = 133;
			addRecipe();
			newRecipe.createItem.SetDefaults("Adamantite Helmet");
			newRecipe.requiredItem[0].SetDefaults(391);
			newRecipe.requiredItem[0].stack = 12;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(402);
			newRecipe.requiredItem[0].SetDefaults(391);
			newRecipe.requiredItem[0].stack = 12;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(400);
			newRecipe.requiredItem[0].SetDefaults(391);
			newRecipe.requiredItem[0].stack = 12;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults("Adamantite Breastplate");
			newRecipe.requiredItem[0].SetDefaults(391);
			newRecipe.requiredItem[0].stack = 24;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults("Adamantite Leggings");
			newRecipe.requiredItem[0].SetDefaults(391);
			newRecipe.requiredItem[0].stack = 18;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults("Adamantite Drill");
			newRecipe.requiredItem[0].SetDefaults(391);
			newRecipe.requiredItem[0].stack = 18;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults("Adamantite Chainsaw");
			newRecipe.requiredItem[0].SetDefaults(391);
			newRecipe.requiredItem[0].stack = 12;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults("Adamantite Repeater");
			newRecipe.requiredItem[0].SetDefaults(391);
			newRecipe.requiredItem[0].stack = 12;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(482);
			newRecipe.requiredItem[0].SetDefaults(391);
			newRecipe.requiredItem[0].stack = 12;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults("Adamantite Glaive");
			newRecipe.requiredItem[0].SetDefaults(391);
			newRecipe.requiredItem[0].stack = 12;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(524);
			newRecipe.requiredItem[0].SetDefaults(366);
			newRecipe.requiredItem[0].stack = 30;
			newRecipe.requiredItem[1].SetDefaults(221);
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(559);
			newRecipe.requiredItem[0].SetDefaults(372);
			newRecipe.requiredItem[1].SetDefaults(377);
			newRecipe.requiredItem[2].SetDefaults(401);
			newRecipe.requiredItem[3].SetDefaults(549);
			newRecipe.requiredItem[3].stack = 20;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(558);
			newRecipe.requiredItem[0].SetDefaults(371);
			newRecipe.requiredItem[1].SetDefaults(376);
			newRecipe.requiredItem[2].SetDefaults(400);
			newRecipe.requiredItem[3].SetDefaults(549);
			newRecipe.requiredItem[3].stack = 20;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(553);
			newRecipe.requiredItem[0].SetDefaults(373);
			newRecipe.requiredItem[1].SetDefaults(378);
			newRecipe.requiredItem[2].SetDefaults(402);
			newRecipe.requiredItem[3].SetDefaults(549);
			newRecipe.requiredItem[3].stack = 20;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(551);
			newRecipe.requiredItem[0].SetDefaults(374);
			newRecipe.requiredItem[1].SetDefaults(379);
			newRecipe.requiredItem[2].SetDefaults(403);
			newRecipe.requiredItem[3].SetDefaults(548);
			newRecipe.requiredItem[3].stack = 20;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(552);
			newRecipe.requiredItem[0].SetDefaults(375);
			newRecipe.requiredItem[1].SetDefaults(380);
			newRecipe.requiredItem[2].SetDefaults(404);
			newRecipe.requiredItem[3].SetDefaults(547);
			newRecipe.requiredItem[3].stack = 20;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(579);
			newRecipe.requiredItem[0].SetDefaults(385);
			newRecipe.requiredItem[1].SetDefaults(386);
			newRecipe.requiredItem[2].SetDefaults(388);
			newRecipe.requiredItem[3].SetDefaults(383);
			newRecipe.requiredItem[4].SetDefaults(384);
			newRecipe.requiredItem[5].SetDefaults(387);
			newRecipe.requiredItem[6].SetDefaults(547);
			newRecipe.requiredItem[6].stack = 5;
			newRecipe.requiredItem[7].SetDefaults(548);
			newRecipe.requiredItem[7].stack = 5;
			newRecipe.requiredItem[8].SetDefaults(549);
			newRecipe.requiredItem[8].stack = 5;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(578);
			newRecipe.requiredItem[0].SetDefaults(435);
			newRecipe.requiredItem[1].SetDefaults(436);
			newRecipe.requiredItem[2].SetDefaults(481);
			newRecipe.requiredItem[3].SetDefaults(549);
			newRecipe.requiredItem[3].stack = 20;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(368);
			newRecipe.requiredItem[0].SetDefaults(483);
			newRecipe.requiredItem[1].SetDefaults(484);
			newRecipe.requiredItem[2].SetDefaults(482);
			newRecipe.requiredItem[3].SetDefaults(548);
			newRecipe.requiredItem[3].stack = 20;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(550);
			newRecipe.requiredItem[0].SetDefaults(537);
			newRecipe.requiredItem[1].SetDefaults(390);
			newRecipe.requiredItem[2].SetDefaults(406);
			newRecipe.requiredItem[3].SetDefaults(547);
			newRecipe.requiredItem[3].stack = 20;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(533);
			newRecipe.requiredItem[0].SetDefaults(98);
			newRecipe.requiredItem[1].SetDefaults(324);
			newRecipe.requiredItem[2].SetDefaults(319);
			newRecipe.requiredItem[2].stack = 5;
			newRecipe.requiredItem[3].SetDefaults(548);
			newRecipe.requiredItem[3].stack = 20;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(561);
			newRecipe.requiredItem[0].SetDefaults(381);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredItem[1].SetDefaults(382);
			newRecipe.requiredItem[1].stack = 10;
			newRecipe.requiredItem[2].SetDefaults(520);
			newRecipe.requiredItem[2].stack = 5;
			newRecipe.requiredItem[3].SetDefaults(548);
			newRecipe.requiredItem[3].stack = 5;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(506);
			newRecipe.requiredItem[0].SetDefaults(20);
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredItem[1].SetDefaults(22);
			newRecipe.requiredItem[1].stack = 20;
			newRecipe.requiredItem[2].SetDefaults(324);
			newRecipe.requiredItem[3].SetDefaults(522);
			newRecipe.requiredItem[3].stack = 35;
			newRecipe.requiredItem[4].SetDefaults(547);
			newRecipe.requiredItem[4].stack = 20;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(494);
			newRecipe.requiredItem[0].SetDefaults(508);
			newRecipe.requiredItem[1].SetDefaults(502);
			newRecipe.requiredItem[1].stack = 25;
			newRecipe.requiredItem[2].SetDefaults(521);
			newRecipe.requiredItem[2].stack = 15;
			newRecipe.requiredItem[3].SetDefaults(19);
			newRecipe.requiredItem[3].stack = 15;
			newRecipe.requiredItem[4].SetDefaults(549);
			newRecipe.requiredItem[4].stack = 20;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(425);
			newRecipe.requiredItem[0].SetDefaults(507);
			newRecipe.requiredItem[1].SetDefaults(501);
			newRecipe.requiredItem[1].stack = 80;
			newRecipe.requiredItem[2].SetDefaults(520);
			newRecipe.requiredItem[2].stack = 15;
			newRecipe.requiredItem[3].SetDefaults(19);
			newRecipe.requiredItem[3].stack = 15;
			newRecipe.requiredItem[4].SetDefaults(549);
			newRecipe.requiredItem[4].stack = 20;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(497);
			newRecipe.requiredItem[0].SetDefaults(275);
			newRecipe.requiredItem[0].stack = 15;
			newRecipe.requiredItem[1].SetDefaults(319);
			newRecipe.requiredItem[1].stack = 5;
			newRecipe.requiredItem[2].SetDefaults(261);
			newRecipe.requiredItem[2].stack = 15;
			newRecipe.requiredItem[3].SetDefaults(520);
			newRecipe.requiredItem[3].stack = 5;
			newRecipe.requiredItem[4].SetDefaults(521);
			newRecipe.requiredItem[4].stack = 5;
			newRecipe.requiredItem[5].SetDefaults(547);
			newRecipe.requiredItem[5].stack = 20;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(495);
			newRecipe.requiredItem[0].SetDefaults(502);
			newRecipe.requiredItem[0].stack = 30;
			newRecipe.requiredItem[1].SetDefaults(526);
			newRecipe.requiredItem[1].stack = 4;
			newRecipe.requiredItem[2].SetDefaults(501);
			newRecipe.requiredItem[2].stack = 60;
			newRecipe.requiredItem[3].SetDefaults(520);
			newRecipe.requiredItem[3].stack = 10;
			newRecipe.requiredItem[4].SetDefaults(549);
			newRecipe.requiredItem[4].stack = 20;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(493);
			newRecipe.requiredItem[0].SetDefaults(320);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredItem[1].SetDefaults(575);
			newRecipe.requiredItem[1].stack = 25;
			newRecipe.requiredItem[2].SetDefaults(520);
			newRecipe.requiredItem[2].stack = 30;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(492);
			newRecipe.requiredItem[0].SetDefaults(320);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredItem[1].SetDefaults(575);
			newRecipe.requiredItem[1].stack = 25;
			newRecipe.requiredItem[2].SetDefaults(521);
			newRecipe.requiredItem[2].stack = 30;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(394);
			newRecipe.requiredItem[0].SetDefaults(187);
			newRecipe.requiredItem[1].SetDefaults(268);
			newRecipe.requiredTile[0] = 114;
			addRecipe();
			newRecipe.createItem.SetDefaults(395);
			newRecipe.requiredItem[0].SetDefaults(17);
			newRecipe.requiredItem[1].SetDefaults(18);
			newRecipe.requiredItem[2].SetDefaults(393);
			newRecipe.requiredTile[0] = 114;
			addRecipe();
			newRecipe.createItem.SetDefaults(396);
			newRecipe.requiredItem[0].SetDefaults(158);
			newRecipe.requiredItem[1].SetDefaults(193);
			newRecipe.requiredTile[0] = 114;
			addRecipe();
			newRecipe.createItem.SetDefaults(397);
			newRecipe.requiredItem[0].SetDefaults(156);
			newRecipe.requiredItem[1].SetDefaults(193);
			newRecipe.requiredTile[0] = 114;
			addRecipe();
			newRecipe.createItem.SetDefaults(399);
			newRecipe.requiredItem[0].SetDefaults(53);
			newRecipe.requiredItem[1].SetDefaults(159);
			newRecipe.requiredTile[0] = 114;
			addRecipe();
			newRecipe.createItem.SetDefaults(405);
			newRecipe.requiredItem[0].SetDefaults(54);
			newRecipe.requiredItem[1].SetDefaults(128);
			newRecipe.requiredTile[0] = 114;
			addRecipe();
			newRecipe.createItem.SetDefaults(555);
			newRecipe.requiredItem[0].SetDefaults(223);
			newRecipe.requiredItem[1].SetDefaults(189);
			newRecipe.requiredTile[0] = 114;
			addRecipe();
			newRecipe.createItem.SetDefaults(511);
			newRecipe.requiredItem[0].SetDefaults(3);
			newRecipe.requiredItem[1].SetDefaults(530);
			addRecipe();
			newRecipe.createItem.SetDefaults(512);
			newRecipe.requiredItem[0].SetDefaults(26);
			newRecipe.requiredItem[0].stack = 4;
			newRecipe.requiredItem[1].SetDefaults(530);
			addRecipe();
			newRecipe.createItem.SetDefaults(580);
			newRecipe.requiredItem[0].SetDefaults(167);
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredItem[1].SetDefaults("Wire");
			addRecipe();
			newRecipe.createItem.SetDefaults(581);
			newRecipe.requiredItem[0].SetDefaults("Iron Bar");
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredItem[1].SetDefaults("Wire");
			newRecipe.requiredItem[1].stack = 2;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(582);
			newRecipe.requiredItem[0].SetDefaults("Iron Bar");
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredItem[1].SetDefaults("Wire");
			newRecipe.requiredItem[1].stack = 2;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(583);
			newRecipe.requiredItem[0].SetDefaults(17);
			newRecipe.requiredItem[1].SetDefaults("Iron Bar");
			newRecipe.requiredItem[1].stack = 5;
			newRecipe.requiredItem[2].SetDefaults("Wire");
			newRecipe.requiredItem[2].stack = 1;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(584);
			newRecipe.requiredItem[0].SetDefaults(16);
			newRecipe.requiredItem[1].SetDefaults("Iron Bar");
			newRecipe.requiredItem[1].stack = 5;
			newRecipe.requiredItem[2].SetDefaults("Wire");
			newRecipe.requiredItem[2].stack = 1;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(585);
			newRecipe.requiredItem[0].SetDefaults(15);
			newRecipe.requiredItem[1].SetDefaults("Iron Bar");
			newRecipe.requiredItem[1].stack = 5;
			newRecipe.requiredItem[2].SetDefaults("Wire");
			newRecipe.requiredItem[2].stack = 1;
			newRecipe.requiredTile[0] = 16;
			addRecipe();
			newRecipe.createItem.SetDefaults(540);
			newRecipe.requiredItem[0].SetDefaults(3);
			newRecipe.requiredItem[0].stack = 6;
			newRecipe.requiredTile[0] = 114;
			addRecipe();
			newRecipe.createItem.SetDefaults(565);
			newRecipe.requiredItem[0].SetDefaults(562);
			newRecipe.requiredItem[1].SetDefaults(563);
			newRecipe.requiredItem[2].SetDefaults(564);
			newRecipe.requiredItem[3].SetDefaults(566);
			newRecipe.requiredItem[4].SetDefaults(567);
			newRecipe.requiredItem[5].SetDefaults(568);
			newRecipe.requiredItem[6].SetDefaults(569);
			newRecipe.requiredItem[7].SetDefaults(570);
			newRecipe.requiredItem[8].SetDefaults(571);
			newRecipe.requiredItem[9].SetDefaults(572);
			newRecipe.requiredItem[10].SetDefaults(573);
			newRecipe.requiredItem[11].SetDefaults(574);
			newRecipe.requiredTile[0] = 114;
			addRecipe();
			newRecipe.createItem.SetDefaults("Depth Meter");
			newRecipe.requiredItem[0].SetDefaults(20);
			newRecipe.requiredItem[0].stack = 10;
			newRecipe.requiredItem[1].SetDefaults(21);
			newRecipe.requiredItem[1].stack = 8;
			newRecipe.requiredItem[2].SetDefaults(19);
			newRecipe.requiredItem[2].stack = 6;
			newRecipe.requiredTile[0] = 14;
			newRecipe.requiredTile[1] = 15;
			addRecipe();
			newRecipe.createItem.SetDefaults(193);
			newRecipe.requiredItem[0].SetDefaults(173);
			newRecipe.requiredItem[0].stack = 20;
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults(518);
			newRecipe.requiredItem[0].SetDefaults(531);
			newRecipe.requiredItem[1].SetDefaults(502);
			newRecipe.requiredItem[1].stack = 30;
			newRecipe.requiredItem[2].SetDefaults(520);
			newRecipe.requiredItem[2].stack = 20;
			newRecipe.requiredTile[0] = 101;
			addRecipe();
			newRecipe.createItem.SetDefaults(519);
			newRecipe.requiredItem[0].SetDefaults(531);
			newRecipe.requiredItem[1].SetDefaults(522);
			newRecipe.requiredItem[1].stack = 30;
			newRecipe.requiredItem[2].SetDefaults(521);
			newRecipe.requiredItem[2].stack = 20;
			newRecipe.requiredTile[0] = 101;
			addRecipe();
			newRecipe.createItem.SetDefaults("Goggles");
			newRecipe.requiredItem[0].SetDefaults(38);
			newRecipe.requiredItem[0].stack = 2;
			newRecipe.requiredTile[0] = 18;
			newRecipe.requiredTile[1] = 15;
			addRecipe();
			newRecipe.createItem.SetDefaults(266);
			newRecipe.requiredItem[0].SetDefaults(324);
			newRecipe.requiredItem[1].SetDefaults(323);
			newRecipe.requiredItem[1].stack = 10;
			newRecipe.requiredItem[2].SetDefaults(180);
			newRecipe.requiredItem[2].stack = 5;
			newRecipe.requiredTile[0] = 17;
			addRecipe();
			newRecipe.createItem.SetDefaults("Sunglasses");
			newRecipe.requiredItem[0].SetDefaults("Black Lens");
			newRecipe.requiredItem[0].stack = 2;
			newRecipe.requiredTile[0] = 18;
			newRecipe.requiredTile[1] = 15;
			addRecipe();
			newRecipe.createItem.SetDefaults("Mana Crystal");
			newRecipe.requiredItem[0].SetDefaults(75);
			newRecipe.requiredItem[0].stack = 10;
			addRecipe();
			newRecipe.createItem.SetDefaults(43);
			newRecipe.requiredItem[0].SetDefaults(38);
			newRecipe.requiredItem[0].stack = 6;
			newRecipe.requiredTile[0] = 26;
			addRecipe();
			newRecipe.createItem.SetDefaults(70);
			newRecipe.requiredItem[0].SetDefaults(67);
			newRecipe.requiredItem[0].stack = 30;
			newRecipe.requiredItem[1].SetDefaults(68);
			newRecipe.requiredItem[1].stack = 15;
			newRecipe.requiredTile[0] = 26;
			addRecipe();
			newRecipe.createItem.SetDefaults(560);
			newRecipe.requiredItem[0].SetDefaults(23);
			newRecipe.requiredItem[0].stack = 99;
			newRecipe.requiredItem[1].SetDefaults(264);
			newRecipe.requiredTile[0] = 26;
			addRecipe();
			newRecipe.createItem.SetDefaults(544);
			newRecipe.requiredItem[0].SetDefaults(38);
			newRecipe.requiredItem[0].stack = 3;
			newRecipe.requiredItem[1].SetDefaults(20);
			newRecipe.requiredItem[1].stack = 5;
			newRecipe.requiredItem[2].SetDefaults(22);
			newRecipe.requiredItem[2].stack = 5;
			newRecipe.requiredItem[3].SetDefaults(520);
			newRecipe.requiredItem[3].stack = 7;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(556);
			newRecipe.requiredItem[0].SetDefaults(68);
			newRecipe.requiredItem[0].stack = 6;
			newRecipe.requiredItem[1].SetDefaults(20);
			newRecipe.requiredItem[1].stack = 5;
			newRecipe.requiredItem[2].SetDefaults(22);
			newRecipe.requiredItem[2].stack = 5;
			newRecipe.requiredItem[3].SetDefaults(521);
			newRecipe.requiredItem[3].stack = 7;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(557);
			newRecipe.requiredItem[0].SetDefaults(154);
			newRecipe.requiredItem[0].stack = 30;
			newRecipe.requiredItem[1].SetDefaults(20);
			newRecipe.requiredItem[1].stack = 5;
			newRecipe.requiredItem[2].SetDefaults(22);
			newRecipe.requiredItem[2].stack = 5;
			newRecipe.requiredItem[3].SetDefaults(520);
			newRecipe.requiredItem[3].stack = 5;
			newRecipe.requiredItem[4].SetDefaults(521);
			newRecipe.requiredItem[4].stack = 5;
			newRecipe.requiredTile[0] = 134;
			addRecipe();
			newRecipe.createItem.SetDefaults(71);
			newRecipe.createItem.stack = 100;
			newRecipe.requiredItem[0].SetDefaults(72);
			newRecipe.requiredItem[0].stack = 1;
			addRecipe();
			newRecipe.createItem.SetDefaults(72);
			newRecipe.createItem.stack = 1;
			newRecipe.requiredItem[0].SetDefaults(71);
			newRecipe.requiredItem[0].stack = 100;
			addRecipe();
			newRecipe.createItem.SetDefaults(72);
			newRecipe.createItem.stack = 100;
			newRecipe.requiredItem[0].SetDefaults(73);
			newRecipe.requiredItem[0].stack = 1;
			addRecipe();
			newRecipe.createItem.SetDefaults(73);
			newRecipe.createItem.stack = 1;
			newRecipe.requiredItem[0].SetDefaults(72);
			newRecipe.requiredItem[0].stack = 100;
			addRecipe();
			newRecipe.createItem.SetDefaults(73);
			newRecipe.createItem.stack = 100;
			newRecipe.requiredItem[0].SetDefaults(74);
			newRecipe.requiredItem[0].stack = 1;
			addRecipe();
			newRecipe.createItem.SetDefaults(74);
			newRecipe.createItem.stack = 1;
			newRecipe.requiredItem[0].SetDefaults(73);
			newRecipe.requiredItem[0].stack = 100;
			addRecipe();
			for (int i = 0; i < numRecipes; i++)
			{
				for (int j = 0; Main.recipe[i].requiredItem[j].type > 0; j++)
				{
					Main.recipe[i].requiredItem[j].checkMat();
				}
				Main.recipe[i].createItem.checkMat();
			}
		}

		public static void addRecipe()
		{
			Main.recipe[numRecipes] = newRecipe;
			newRecipe = new Recipe();
			numRecipes++;
		}

		public static string AddSimpleRecipe(object output, params object[] args)
		{
			if (output is Item)
			{
				newRecipe.createItem.SetDefaults(((Item)output).name);
				newRecipe.createItem.stack = ((Item)output).stack;
			}
			else if (output is string)
			{
				string text = (string)output;
				newRecipe.createItem.SetDefaults(text);
				if (newRecipe.createItem.name == "Unloaded Item")
				{
					string s = text.Split(' ')[0];
					if (!int.TryParse(s, out int result))
					{
						newRecipe = new Recipe();
						throw new Exception("Bad argument for Recipe.addSimpleRecipe(): " + text);
					}
					newRecipe.createItem.SetDefaults(text.Substring(text.IndexOf(' ') + 1));
					if (newRecipe.createItem.name == "Unloaded Item")
					{
						newRecipe = new Recipe();
						throw new Exception("Bad argument for Recipe.addSimpleRecipe(): " + text);
					}
					newRecipe.createItem.stack = result;
				}
			}
			int num = 0;
			int num2 = 0;
			for (int i = 0; i < args.Length; i++)
			{
				if (args[i] is Item)
				{
					newRecipe.requiredItem[num++] = ((Item)args[i]).CloneItem();
					continue;
				}
				if (args[i] is int)
				{
					newRecipe.requiredTile[num2++] = (int)args[i];
					continue;
				}
				if (args[i] is string)
				{
					string text2 = (string)args[i];
					if (text2 == "@Water")
					{
						newRecipe.needWater = true;
						continue;
					}
					if (text2 == "@Lava")
					{
						newRecipe.needLava = true;
						continue;
					}
					if (text2.StartsWith("@"))
					{
						newRecipe.requiredTile[num2++] = Config.tileDefs.ID[text2.Substring(1)];
						continue;
					}
					newRecipe.requiredItem[num].SetDefaults(text2);
					if (newRecipe.requiredItem[num].name == "Unloaded Item")
					{
						string s2 = text2.Split(' ')[0];
						if (!int.TryParse(s2, out int result2))
						{
							newRecipe = new Recipe();
							throw new Exception("Bad argument for Recipe.addSimpleRecipe(): " + text2);
						}
						newRecipe.requiredItem[num].SetDefaults(text2.Substring(text2.IndexOf(' ') + 1));
						if (newRecipe.requiredItem[num].name == "Unloaded Item")
						{
							newRecipe = new Recipe();
							throw new Exception("Bad argument for Recipe.addSimpleRecipe(): " + text2);
						}
						newRecipe.requiredItem[num].stack = result2;
					}
					num++;
					continue;
				}
				newRecipe = new Recipe();
				throw new Exception("Bad argument type for Recipe.addSimpleRecipe(): " + args[i].GetType().Name);
			}
			Array.Resize(ref Main.recipe, Main.recipe.Length + 1);
			addRecipe();
			for (int j = 0; Main.recipe[numRecipes - 1].requiredItem[j].type > 0; j++)
			{
				Main.recipe[numRecipes - 1].requiredItem[j].checkMat();
			}
			Main.recipe[numRecipes - 1].createItem.checkMat();
			string text3 = "tConfigSimpleRecipe" + nextSimpleRecipe++;
			Config.recipeByName[text3] = Main.recipe[numRecipes - 1];
			return text3;
		}
	}
}
